title: ACF Pro Table Field add-on

collections:
    filters:
        output: true,
        permalink: filters/:path/

    topics:
        output: true,
        permalink: topics/:path/


urls:
    filters: filters/
    topics: topics/
